### ISSUE TITLE
APK lacks (v1/v2) signatures

### ISSUE THREAD

**Issue by IzzySoft** [HardcodeCoder/PulseMusic#1]
According to the Readme, PulseMusic supports Android 5 – but `apksigner` complains it cannot find any signatures:

```
$ apksigner verify --verbose PulseMusic_v2.0.0_release.apk 
DOES NOT VERIFY
ERROR: No JAR signatures
```

In case you signed the APK v3 only: v2 was introduced with Android 7 – so all below will require v1 signing as well; best tick all 3 boxes (v1, v2 and v3).

Could you please update the attached APK with a fully signed one? Thanks!

**Comment by HardcodeCoder** [comment]
Next release will be signed correctly. I will try to update the current (v2.0.0) or else attach a file here

**Comment by IzzySoft** [comment]
Thanks! Please let me know (here) once a signed APK is attached to the release.

**Comment by HardcodeCoder** [comment]
I have updated the release you can check it out.
```
apksigner verify --verbose PulseMusic_v2.0.0_released_signed.apk 
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
```
Please ignore the warning as of now
`WARNING: META-INF/androidx.*.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
`
Note: There was some styling/theme issue in api <=23 as of v2.0.0. (That has been fixed in upcoming build)

**Comment by IzzySoft** [comment]
Thanks! That worked out fine. To promote your app and make it easier to find as well as install/update, I've just [added it to my repo](https://apt.izzysoft.de/fdroid/index/apk/com.hardcodecoder.pulsemusic) (the [VT notification](https://www.virustotal.com/gui/file/e77c3b1c063e525b0cc38844aa45da8fc744650daa8b45d5719692af3c0489b1/detection/f-e77c3b1c063e525b0cc38844aa45da8fc744650daa8b45d5719692af3c0489b1-1597856603) can be ignored: that MS scanner "finds" this Windows-thingy in many apps recently, so it's almost certainly a false positive – especially as it's a Win32 thingy). If you want some screenshots added, just let me know. As soon as you crate a new tag and attach an APK to it, my updater will automatically grab that within 24h, so users will stay up-to-date.

Thanks again for your help!

**Comment by HardcodeCoder** [comment]
Thank you. I will be releasing V3 in couple of days and that's going to be a major release (300+ commits since V2) so will add screenshots from V3, you can share yours as well.

**Comment by IzzySoft** [comment]
Cool! A pointer: to make distribution easier, you might consider establishing [Fastlane structures](https://gitlab.com/snippets/1895688). Those are a standard used by many services (e.g. F-Droid highly recommend that – disclosure: I'm one of the maintainers there, so once you've opened an [RFP](https://gitlab.com/fdroid/rfp/issues) at F-Droid, we'll meet there again) and also can be used to publish on Google Play (should you plan doing that). I'd then pick screenshots from there – and in case you also provide per-release changelogs via Fastlane, my updater can pull those automatically, too. Just let me know when it's there, so I set things up.
