### ISSUE TITLE
[BUG] When having a lot of excluded folder, the 'add new blacklisted folder'-button can not be clicked due to layout

### ISSUE THREAD

**Issue by pietervdvn** [HardcodeCoder/PulseMusic#114]
**Describe the bug**

When there are a lot of ignored folders, the list of ignored folders is shown above the title. When attempting to click the button to add one more folder, the 'remove' button is clicked instead:

![signal-2021-04-29-235249](https://user-images.githubusercontent.com/1466478/116623236-39f38e80-a946-11eb-9664-28059029e8df.png)

**Steps to reproduce the behavior:**
1. Go to Settings > General -> Select ignored folders
2. Add tons of ignored folders (~15)
2. Save and open 'Select ignored folders' again
3. Click the 'add new ignored folders'-button
4. The top item of the list is removed from the list

**Expected behavior**

The dialog for a new folder should be opened

**Screenshots**
See above

**Device and Version Info (please complete the following information):**
 - Device: Xiaomi 9T Pro / Redmi K20
 - OS: DotOS
 - Android Version: 11
 - App Version: 4.1.1 - 210040101 (via FDroid)

PS: the app looks really cool!

**Comment by HardcodeCoder** [comment]
This should be easy to fix.
