### ISSUE TITLE
[Enhancement] Allow to ignore more folders

### ISSUE THREAD

**Issue by pietervdvn** [HardcodeCoder/PulseMusic#115]
**Is the enhancement related to a problem? Please describe.**

I have a full backup of all my files on my phone; this contains some assets of old coding projects with sounds and stuff.
I would like to disable this entire directory at once; but this is not possible, as only some files are shown

Also see #114

**Describe the solution you'd like**

The ignore-folder-dialog could show not only directories with sound assets, but also their parent directories all the way up. Alternatively, a 'pick folder'-dialog would be cool too.

**Comment by HardcodeCoder** [comment]
If I understand correctly you have something like this `dir1/dir2/dir3/audio.mp3` and you want to not only display `dir3` but also `dir1` or `dir2` in the ignore folder selection page?

If that's the case  it will be easy to implement (as per my initial understanding) or adding a pickup dialog. Lets see which one fits best

**Comment by pietervdvn** [comment]
> If I understand correctly you have something like this dir1/dir2/dir3/audio.mp3 and you want to not only display dir3 but also dir1 or dir2 in the ignore folder selection page?

Jup, indeed; that would work.

**Comment by pietervdvn** [comment]
Thanks for the fix! Looking forward to the update...
