### ISSUE TITLE
[BUG] Pulse omits shorts songs or interludes

### ISSUE THREAD

**Issue by Mederim** [HardcodeCoder/PulseMusic#116]
When i downloaded the HUMANZ Gorillaz album i not see the most interludes only one that is 1:00 minutes and when i see my other artists with shorts songs loke 10 seconds Pulse not show the songs

**Comment by HardcodeCoder** [comment]
This is not a bug  It's a feature. Pulse filters out music files with duration less than 30 seconds by default. To turn this off, go to Settings-> General -> Duration filter, and set the value to 0. Then restart the app. You will see all the songs in the app.
