### ISSUE TITLE
Folder exclusions /include

### ISSUE THREAD

**Issue by aha999** [HardcodeCoder/PulseMusic#12]
Currently, i couldn't find an option in the settings to exclude certain folders from scanning for sound files.

Please include an option to include or remove folders from scanning.

**Comment by HardcodeCoder** [comment]
Pulse Music uses Android database `MediaStore` to retrieve song data, it does not scan your storage for media files itself. So adding the option to exclude folders is not possible, specially given the limited access to storage from Api 29+.

**Comment by aha999** [comment]
Phonograph (open source music app) has a blacklist where i can blacklist all the folders i don't want..."the content of blacklisted folders is hidden from your library".

**Comment by HardcodeCoder** [comment]
Okay i got your request. Will see if i can implement something similar.
