### ISSUE TITLE
(Regular) f-droid releases 

### ISSUE THREAD

**Issue by data-niklas** [HardcodeCoder/PulseMusic#16]
Will there be another f-droid release soon?
And will there be regular releases, or will another version be released, when the app feels stable and there have been enough changes?

**Comment by HardcodeCoder** [comment]
`V4.0.0` is out. I wish to provide update monthly but, since there were a few breaking changes, this version took a little longer than expected.

**Comment by data-niklas** [comment]
nice

**Comment by offa** [comment]
> Will there be another f-droid release soon?

Is there already a F-Droid release? I can't find it there.
