### ISSUE TITLE
Crash in v4.0.0

### ISSUE THREAD

**Issue by Mk1378** [HardcodeCoder/PulseMusic#17]
Every time I open the app it crashes after 1 second!

**Comment by HardcodeCoder** [comment]
Did you uninstalled previous version and cleared data before installing this version?

**Comment by Mk1378** [comment]
Yes

**Comment by HardcodeCoder** [comment]
Can you provide logs?

**Comment by Mk1378** [comment]
Where are they?

**Comment by HardcodeCoder** [comment]
Use [Logcat Reader](https://play.google.com/store/apps/details?id=com.dp.logcatapp). Follow the steps to grant required permissions, then start recording. Open the Pulse music app, let the app crash, then you will get the crash logs in logcat reader. Send it here.

**Comment by Mk1378** [comment]
Logs:

https://paste.ee/p/mrrKw

**Comment by HardcodeCoder** [comment]
These logs are not from Pulse music. Which app did you use to take logs?  Looks like these logs are from the log reader app itself

**Comment by HardcodeCoder** [comment]
Extract the zip, you will find a debug app. Install this debug app. Open the app and let it crash. Then, open any file manager and navigate to  `Android/data/com.hardcodecoder.pulsemusic/files/`, you wil most probably see a `logcat.txt` file. Send me that.
[app-debug.zip](https://github.com/HardcodeCoder/PulseMusic/files/5435538/app-debug.zip)

**Comment by data-niklas** [comment]
I also get that Error, seems like the Resource "ic_audio_48dp.xml" was not found

**Comment by HardcodeCoder** [comment]
> I also get that Error, seems like the Resource "drawable/ic_audio_48dp.xml" was not found
> [Log, filtered by PulseMusic and Error](https://paste.ee/p/sKriO)

Does the app crashes after 1 sec of opening it?
What's weird is that `ic_audio_48dp.xml` is present under drawables, why then File not found exception. 🤔

**Comment by HardcodeCoder** [comment]
Okay I am able to reproduce the issue. It happens if you don't have album art for any track, glide tries to load the fallback icon and fails. To fix this try settings an album art using a tag editor. I will provide a fix soon.

**Comment by Mk1378** [comment]
Logs are [here](https://paste.ee/p/ZylhR) but the debug version doesn't crash.
