### ISSUE TITLE
Exclude folders doesn't work

### ISSUE THREAD

**Issue by aha999** [HardcodeCoder/PulseMusic#20]
when excluded folders are set, the files in that folders aren't excluded/blacklisted, so they are still in the library.

**Comment by HardcodeCoder** [comment]
Provide a screenshot of ignored folders list

**Comment by aha999** [comment]
![Screenshot_20201108-200132_Pulse_Music](https://user-images.githubusercontent.com/50620416/98481836-7a771880-21fd-11eb-92b9-d2c47fb4ae7c.png)

**Comment by HardcodeCoder** [comment]
All these folders are in your internal storage or some of them are in a memory card?.

**Comment by aha999** [comment]
they are from both memories... some internal, some external
