### ISSUE TITLE
Blacklisting Directories asks for Read Permission on that directory

### ISSUE THREAD

**Issue by Nesaijn** [HardcodeCoder/PulseMusic#21]
Why is that?
Another music player app also has this function but does not need read permission on that directories.

LineageOS 17
Pulse Music V4.0.1

**Comment by HardcodeCoder** [comment]
As of Android 10 app needs read permission on each folder to even get the folders name(Atleast i haven't seen any workaround either). Those other music players are using "legacy" mode and hence does not need that permission. But eventually when those app migrate to using SAF (Storage Access Framework) they too will need that permission.

If you are worried about privacy, app cannot access any file directly on your storage even if you grant permission to each folder. As of android 10 all file operations are securely handled by the system and not by the application itself.
