### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by FireRedDev** [HardcodeCoder/PulseMusic#22]
Hi how do mood suggestions work? Why not just have a button like spotify that generates a smart playlist for stuff like relaxing, workout, party, ... 
And an option to start a random radio from one song would be great
On my s10 the main menu texts dont have padding

**Comment by HardcodeCoder** [comment]
_"an option to start a random radio from one song would be great"_ **can you elaborate a bit more?**
_"On my s10 the main menu texts dont have padding"_ **providing a screenshot for the same will be helpful.**

**Comment by dalaeance** [comment]
Seems OP disappeared, but that sounds like a cool idea. An implementation that immediately comes to mind is generating playlists based on beats per minute.

**Comment by HardcodeCoder** [comment]
@dalaeance I am not sure, if I get it correct. Can you explain what you mean by "beats per minute".

**Comment by dalaeance** [comment]
Beats per minute, or BPM, refers to the tempo of the music. Tempo often affects one's mood. A higher tempo tends to get us pumped up, while a lower tempo tends to help us relax. This is generally true, regardless of the track's genre.

**Comment by HardcodeCoder** [comment]
I thought it might be something like that. Well this is not feasible to implement (or maybe i don't know how). In android we don't have these info (tempo data) available, and calculating them manually for each track is not an option (lot of computing is required). So, this will not be implemented.
