### ISSUE TITLE
repeat only repeats once, then disables itself

### ISSUE THREAD

**Issue by minusfourty** [HardcodeCoder/PulseMusic#25]
When trying to play a song on repeat, it will repeat as intended the first time, but after it repeats repeat is no longer selected, and it either moves on to the next song, or stops completely if it's the last in an album.

**Comment by HardcodeCoder** [comment]
That's the expected behaviour. The option repeats the track only once(The icon itself clearly shows that it will repeat once). What you are looking for is infinite loop which is not available as of now.
