### ISSUE TITLE
App crash when going to playlists screen.

### ISSUE THREAD

**Issue by ModdedGamers** [HardcodeCoder/PulseMusic#3]
Phone: Moto g6
Android 9 Pie
App Version: 3 from IzzySoft Repo.

Whenever I go to the playlist screen, the app crashes. I don't know why.

**Comment by HardcodeCoder** [comment]
> Phone: Moto g6
> Android 9 Pie
> App Version: 3 from IzzySoft Repo.
> 
> Whenever I go to the playlist screen, the app crashes. I don't know why.

Did you previously installed V2? Try clearing data and cache

**Comment by ModdedGamers** [comment]
After clearing cache and storage, app still crashes.
