### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [HardcodeCoder/PulseMusic#30]
Can PulseMusic be translated ?

But I can't do a pulse request, so we'll have to do it differently.

In 4.0.3, for example, there are English and German words in it.

**Comment by HardcodeCoder** [comment]
Yes, Pulse Music is open for translations.
Since you cannot create a pull request I have set up [Crowdin](https://crwd.in/pulse-music)
You can submit your translations there.
The translations will reflect in the next update.

**Comment by mondlicht-und-sterne** [comment]
Nice. On crowdin i have an account. Big thanks.

**Comment by HardcodeCoder** [comment]
I am closing this issue now. Feel free to comment down below for further queries.
