### ISSUE TITLE
Crowdin German

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [HardcodeCoder/PulseMusic#32]
https://crowdin.com/project/pulse-music/de

i finished the german translation, more languages will follow in 2021, which i will translate.

**Comment by HardcodeCoder** [comment]
Thanks. I will update the translations. Just wondering how many languages you know. :)

**Comment by mondlicht-und-sterne** [comment]
it would be too much to write them all down :)
others are also surprised, but are happy when they can offer their app in several or many languages.
