### ISSUE TITLE
i promote PulseMusic

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [HardcodeCoder/PulseMusic#34]
i paint fdroid app logos as an acrylic painting and and then promote it on mastodon and pixelfed 

here the links zu PulseMusic

#pixelfed
https://pixelfed.social/p/mondstern/250633871786381312

#mastodon
https://mastodon.technology/@mondstern/105481016957643936

**Comment by HardcodeCoder** [comment]
Thanks your for support and the awesome art. 
However, I do encourage you to not create a new issue(s) for such things.
You can interact via the discussion sections.
