### ISSUE TITLE
Music covers are not displayed

### ISSUE THREAD

**Issue by Beowulf2** [HardcodeCoder/PulseMusic#40]
### Steps to reproduce
1. Open App
2. Have music with cover in storage

### Expected behaviour
- The music cover is displayed

### Actual behaviour
- The music cover is not displayed (for example the file manager displays them)

### Environment data
Android version: 9

Device-Model: Moto G6

App version: 4.0.5

### Screenshot
![Screenshot_20210117-172322](https://user-images.githubusercontent.com/60288895/104849208-e0140f00-58e8-11eb-92be-6f4efda18591.png)

**Comment by HardcodeCoder** [comment]
This may not necessarily be a bug. The app completely depends on `MediaStore` to provide all the track info (including media cover art).
An easy fix might be to restart the phone and check again.

**Comment by Beowulf2** [comment]
Ok, I tested a little bit and I think the problem is, that the Music-Files are on the SD-Card maybe a problem with the permissions?

**Comment by Beowulf2** [comment]
When I restart my phone, all files (excepted the files on the internal storage) are gone. To fix that I must delete the app data and then the files are back wihtout covers.

**Comment by HardcodeCoder** [comment]
> Ok, I tested a little bit and I think the problem is, that the Music-Files are on the SD-Card maybe a problem with the permissions?

If the app is able to play the tracks then there is no issue with permissions. 



> When I restart my phone, all files (excepted the files on the internal storage) are gone. To fix that I must delete the app data and then the files are back wihtout covers.

This happens because `MediaStore` rescans your storage after a reboot and it might take few seconds to a couple of minutes before the data is available for app to access. 


1. Are the album art from tracks in internal storage displayed? 
   If so then it might be that `MediaStore` is not extracting 
   albumm art from tracks in SD-card.

If none of the album art are getting displayed then 
 Try V4.0.3 and see see if that works.

**Comment by Beowulf2** [comment]
> If the app is able to play the tracks then there is no issue with permissions.  
Yes you right I forgot that...  

> This happens because MediaStore rescans your storage after a reboot and it might take few seconds to a couple of minutes before the data is available for app to access.  
When I waited, the tracks didn't come back into the app (restarting the app didn't help either).
Recently, even deleting the data and restarting the app didn't help...  
I'll probably try a bit more to find out how this error occurs...

**Comment by Beowulf2** [comment]
I fixed it in the Pull Request

**Comment by HardcodeCoder** [comment]
Can you please confirm this:
1. Does album art from tracks in internal storage displayed correctly before the changes in #42? Or only the tracks in SD-card were having trouble displaying album art?

**Comment by Beowulf2** [comment]
I must test this in an AVD, because now the albums art are displayed every time, also without write permission, because now they already exist...

**Comment by HardcodeCoder** [comment]
You can try uninstalling the app and deleting `.thumbnails` folder and may be restart the device. I think that will erase the track thumbnails.
I will wait for a confirmation before merging.

**Comment by Beowulf2** [comment]
Ok, I was able to reproduce the error (the first time I deleted the wrong thumbnails folder)  
After I copied one album from the SD-Card to the internal storage, I noticed that this has also no album art...  
Should I check if its shown, when I install this version, for internal stored music?

**Comment by HardcodeCoder** [comment]
Do this:
1. Uninstall Pulse Music
2. Delete .thumbnails folder.
3. Restart the device.
Now, you sre back to the original state with some of the tracks in Internal storage and some in SD-card.

4. Install Pulse music V4.0.5
5. Check which tracks are showing album art.
6. See if the tracks in Internal storage are also missing album art or only those in SD-card.

**Comment by Beowulf2** [comment]
Nope, no album art, but know I have again the bug, that no music from the SD-Card are shown, but this should also fixed with #42 (I have never had the problem with that version)

**Comment by Beowulf2** [comment]
I think it tries to store all thumbnails on the SD-Card

**Comment by HardcodeCoder** [comment]
Maybe is your SD-card formatted as portable storage or internal storage? 
I tested this on android 9 with and without SD-card (formatted as portable storage), and it works fine. 
Anyways, I will be merging this now.

**Comment by Beowulf2** [comment]
My SD-Card is formated as portable storage...  
Anyway Android tries for every cover to store it on the SD-Card in Android->Data->com.google.android.vending (I think, not 100% sure about the path, when interested in it I can look again)

**Comment by HardcodeCoder** [comment]
I see. In my device(Android 10) its in `Internal storage/Music/.thumbnails/`. May be different oem has a different impl. or different android versions store thumbnails differently.
Anyways thanks for your help so far. I have .merged the changes.

**Comment by OliverLew** [comment]
@HardcodeCoder I still have this problem. I am on Android 11 (oneplus hydrogen OS). I have:
- installed version 4.0.6
- deleted .thumbnails folder in Music (I have searched, that's the only one related to music files).
- cleared app data
- restarted phone

But the music file covers are still not shown.

**Comment by HardcodeCoder** [comment]
Thanks for reporting the issue. But as of now Pulse Music does not target Android 11 (Basically untested on Android 11). I will look into the issue after targeting to Android 11.

**Comment by Beowulf2** [comment]
@OliverLew Can you try restart your phone, whitout deleting the .thumbnail folder?

**Comment by OliverLew** [comment]
@Beowulf2 no, tried both go straight restarting and restart after clearing all app data, both not showing music covers. There are thumbnails in the folder when I tested it.
