### ISSUE TITLE
Why it can't show in any file manager

### ISSUE THREAD

**Issue by Pranab009** [HardcodeCoder/PulseMusic#45]
It can't show in any file manager. You can't play any music from file manager because it can't show.

**Comment by Beowulf2** [comment]
You can show the file manager, by clicking at the home screen, on the "select track" icon, also it should load your music files automatic (when the files are stored on the SD-Card, you must wait for the next release, or build from source, because there is a bug, which is already fixed, but not in the newest release).

**Comment by Beowulf2** [comment]
>  (when the files are stored on the SD-Card, you must wait for the next release, or build from source, because there is a bug, which is already fixed, but not in the newest release)

Or restart your device, than the music should be shown ;)

**Comment by HardcodeCoder** [comment]
I think what @Pranab009 meant is the option to open any audio from other file manager via Pulse Music (Similar to how you get to choose which browser to use when opening a url). 
If that's the case, then It's currently not supported.

**Comment by Beowulf2** [comment]
Ok, but this isn't a big thing to implement, when I have time I can (try to) implement this ;)

**Comment by Beowulf2** [comment]
But before I forget, this has to be added to the right activity in the manifest and then you can click on a music file in the file manager, for example, and it opens the app. Then you have to process it in the activity....

```
            <intent-filter>
                <action android:name="android.media.action.MEDIA_PLAY_FROM_SEARCH" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
```

Maybe that already helps ;)

**Comment by HardcodeCoder** [comment]
Yup. I haven't really worked on this stuff. But i think, we also need to add `android:name="android.intent.category.BROWSABLE`
 to the correct activity, which in this case will be the SplashActivity.

**Comment by Beowulf2** [comment]
I think you don't need BROWSABLE... But not 100% sure

**Comment by Beowulf2** [comment]
I checked it, this should be enough und should work...
But it must also implemented in the Activity.

```            <intent-filter>
                <action android:name="android.media.action.MEDIA_PLAY_FROM_SEARCH" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />

                <data android:scheme="content" />
                <data android:mimeType="audio/*" />
                <data android:mimeType="application/ogg" />
                <data android:mimeType="application/x-ogg" />
                <data android:mimeType="application/itunes" />
            </intent-filter>```
