### ISSUE TITLE
No music thumbnails showing

### ISSUE THREAD

**Issue by mizzunet** [HardcodeCoder/PulseMusic#46]
As the title implies, thumbnails are not showing for any song.
![Uploading Screenshot_20210120-202514_Pulse_Music.png…]()

**Comment by mizzunet** [comment]
![Screenshot_20210120-202514_Pulse_Music](https://user-images.githubusercontent.com/10193999/105191983-e7a80380-5af4-11eb-8920-84855a462cba.png)

**Comment by HardcodeCoder** [comment]
This [issues](https://github.com/HardcodeCoder/PulseMusic/issues/40) has already been addressed and [closed](https://github.com/HardcodeCoder/PulseMusic/pull/42)
