### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by avtkal** [HardcodeCoder/PulseMusic#49]
Could it be possible to add a function to edit songs' metadata with Pulse? It would be great to be able to edit songs' names, artists and albums.

**Comment by HardcodeCoder** [comment]
Well, you can use any Tag editor to edit your tracks metadata. It will be a nice addition in Pulse Music.  So maybe in future, I shall implement it.

**Comment by HardcodeCoder** [comment]
Possible duplicate of #27.
