### ISSUE TITLE
Feedback / Feature requests

### ISSUE THREAD

**Issue by data-niklas** [HardcodeCoder/PulseMusic#5]
- Shuffling the queue would be great
    - E.g.: Add a shuffle button to the top right corner of a playlists view
    - Maybe the option, to remove duplicates, could also be added to each playlist
- General settings tab
    - Place for general settings, which will be added in the future
- Clear recent tracks
    - E.g.: Add a button to the top of the recent tracks list, which clears the whole list
- Option to directly open the currently playing playlist from the now playing screen (e.g.: button in the bottom left corner)
- The options to sort songs according to the date they were added (file date)

App looks very modern and beautiful and has all of the basic features to play music so far, but it still lacks some features here and there. PulseMusic is very fast and stays responsive, even with about ~1200 songs

**Comment by HardcodeCoder** [comment]
1. You can delete a playlist by a left swipe gesture.
2. Upto a total of 20 recent tracks are stored and older ones are deleted automatically.

All other features will be added gradually in the future.
Thanks for your valuable feedback.
