### ISSUE TITLE
Read external storage

### ISSUE THREAD

**Issue by chemicalexe** [HardcodeCoder/PulseMusic#51]
how do I gant it read external storage permission?
edit: android pie

**Comment by HardcodeCoder** [comment]
When you open the app for the first time, it will ask you for permission just allow and you are done.

In case you denied, clear app data and cache and open the app again. It will ask you for the permissions.

**Comment by chemicalexe** [comment]
but it can't seem to read music on my sd card

**Comment by HardcodeCoder** [comment]
Please provide info:
Device, Android version, Description of actual issue, any other relevant info related to the issue.

**Comment by chemicalexe** [comment]
Xiaomi redmi note 5 pro, android 9, MIUI 12.

I tried the same sd card on the samsung galaxy a50 (android 10, One UI 2,5) and worked just fine. So it's safe to assume it's a special case on xiaomi devices? 
Now when i got the sd back on my xiaomi i went to my file manger--> Sd card  to make sure nothing is corrupted, opened one of my song from the file manager **using** pulse, song worked just fine, closed pulse, cleared it's cache, opened it and found all my music there.
 
I'm not sure why it wasn't reading it in the first place but did opening that song from sd card using pulse worked as a incentive?

Thanks dev for your attention I really appreciate you taking time to figure the problem.

One more thing, pulse is one of the **_cleanest_** music player i ever used good job man

**Comment by HardcodeCoder** [comment]
It's `MediaStore` which sometimes doesn't index all the songs(Don't know how and why). A simple fix in such cases would be to restart the device which triggers the `MediaScanner` to scan the storage(s) for media file.
