### ISSUE TITLE
[Bug] Music not even playing

### ISSUE THREAD

**Issue by Thewisem** [HardcodeCoder/PulseMusic#55]
The music is not playing. I can't even start a music file from my device. It just crashes itself when I click on a music track.
Device: Samsung galaxy tab A SM P555
OS: Android 7.0 Nougat
Version:4.0.6

**Comment by HardcodeCoder** [comment]
Check if there is any log file inside `Android/data/com.hardcodecoder.pulsemusic/files/`.
Add them with your issue.

**Comment by Thewisem** [comment]
https://user-images.githubusercontent.com/74511929/106635088-80c52880-6591-11eb-8e2d-04b1a7715265.mp4

Wtheck is this? Its going bonkers. And I checked. No logs

**Comment by HardcodeCoder** [comment]
The file paths are broken. Try restarting your tab, that might fix this. There's nothing wrong with the app, when it fails to play a track it tries to play the next track in the queue, but in your case all file paths seems broken and hence the app quickly skils through all the tracks. ear app data and cache and restart your tab.

**Comment by Thewisem** [comment]
Oh Ok Thanks for telling me. And if you could, could you please add a button in the quick settings menu to start or play paused on current music which will start the music and notfication will be there. No FOSS music player does this. Usually musicolet has done this and I like their implementation. :)

**Comment by Thewisem** [comment]
Also It fixed yaaay

**Comment by Thewisem** [comment]
Sorry for disturbing you

**Comment by HardcodeCoder** [comment]
No problem. Glad you got it working. As for the request, I am not sure what you are referring to. We already have three app shortcuts, but these shortcuts only work for Android 7.1 and above.

**Comment by HardcodeCoder** [comment]
Since the original issue is resolved I am closing this.
