### ISSUE TITLE
Question: Is the app on twitter or reddit or the like?

### ISSUE THREAD

**Issue by VivekRagunathan** [HardcodeCoder/PulseMusic#56]

**Comment by HardcodeCoder** [comment]
Pulse Music is currently available on [Github](https://github.com/HardcodeCoder/PulseMusic/releases/latest/) and [f-droid](https://f-droid.org/en/packages/com.hardcodecoder.pulsemusic/)

**Comment by VivekRagunathan** [comment]
Sorry i should have been clearer. I installes from FDroid. What i meant to ask was where do you (prefer) host community discussions, questions etc. Twitter? Reddit? Or here in GitHub?

**Comment by HardcodeCoder** [comment]
Mostly here on Github. But I will be creating a Telegram Group soon.
