### ISSUE TITLE
[Feature Request] allow opening .webm files from file manager with pulse music

### ISSUE THREAD

**Issue by TheSilencedOne** [HardcodeCoder/PulseMusic#60]
I would like to be able to open .webm files from my file manager with pulse music

**Comment by melianmiko** [comment]
Wait, this is a video format. Did you mean that you want to open video files as music?

**Comment by TheSilencedOne** [comment]
> Wait, this is a video format. Did you mean that you want to open video files as music?

.webm is a video and a audio format https://en.m.wikipedia.org/wiki/WebM
And yes I would like to be able to chose pulse music in the
 "open with" menu when selecting a .webm file and have it play as audio, you can play .webm files in the app but can't open them with the app from the file manager 
![Screenshot_20210205-114702_kindlephoto-615500618_1](https://user-images.githubusercontent.com/78061111/107063876-e50e0500-67a8-11eb-8bd2-dc4012aeb341.png)
![Screenshot_20210205-114655_kindlephoto-615384116_1](https://user-images.githubusercontent.com/78061111/107063878-e5a69b80-67a8-11eb-8ff5-614f2159ef63.png)

**Comment by HardcodeCoder** [comment]
Sure. I will have a look.

**Comment by TheSilencedOne** [comment]
> Sure. I will have a look.

Thanks

**Comment by HardcodeCoder** [comment]
I think this cannot be implemented. Android sees `.webm` files as video files (even if it's _**audio only webm**_). So, the system only displays apps that supports video playback. 

I tried encoding `mp3` files to _**audio only webm**_  file, but android still thinks it's a video file.
