### ISSUE TITLE
[Feature Request] Add Quick Setting Tile

### ISSUE THREAD

**Issue by imanincel** [HardcodeCoder/PulseMusic#62]
So it would be easier to listen to the music without opening the app 👌

**Comment by HardcodeCoder** [comment]
Quick settings tile as in the quick options you get by long pressing app icon in the launcher right?
That functionality is already present but works only on Android 7.1 and higher devices, because android doesn't support it before that.

**Comment by imanincel** [comment]
![20210210_130747](https://user-images.githubusercontent.com/77476143/107467513-220b3a80-6ba1-11eb-8053-559434c6975b.jpg)
well, its like that, so you can play directly without opening the app  😁

**Comment by HardcodeCoder** [comment]
Oh! Now I understand. Yes that will be a great addition.
