### ISSUE TITLE
[Feature Request] Default Pages

### ISSUE THREAD

**Issue by putulopi** [HardcodeCoder/PulseMusic#65]
- Adding the lyrics on the music album it could be seen by clicking the album or "show lyrics" button.
- Edit the Album picture with your own.
- Custom Default Pages, when you open the app, you got directed to Album, or Artist Section etc.
- Option to remove the animations.

**Comment by HardcodeCoder** [comment]
Request for tag editor(that includes changing album art) and lyrics support is already an open issue. See #27.
Option to disable animation won't be implemented (Until enough users request this feature). 


P.S.: Updating the title to: [Feature Request] Default Pages
