### ISSUE TITLE
Albums tab bug

### ISSUE THREAD

**Issue by Mk1378** [HardcodeCoder/PulseMusic#7]
As you can see in the screenshot, albums tab doesn't show anything.

![Screenshot_20200827112624](https://user-images.githubusercontent.com/46780868/91407987-56d83f00-e858-11ea-96de-25a78e516bde.jpg)

Steps to reproduce:
Open the app 
Select the albums tab

Device :
Huawei Y7 Prime 2018 
Android 8

**Comment by HardcodeCoder** [comment]
Can you also share the screenshot of Home and Library tab

**Comment by Mk1378** [comment]
Home:

![Screenshot_20200827113552](https://user-images.githubusercontent.com/46780868/91408736-93f10100-e859-11ea-849c-3cd30b9c5306.jpg)

Library:

![Screenshot_20200827113621](https://user-images.githubusercontent.com/46780868/91408751-9bb0a580-e859-11ea-9028-8467dfeeb8e3.jpg)

**Comment by HardcodeCoder** [comment]
The app depends upon android's `MediaStore` to fetch The Songs. Try to restart your phone that should trigger `MediaStore` rescan and check again please.

**Comment by Mk1378** [comment]
I did it but nothing changed.

**Comment by HardcodeCoder** [comment]
> I did it but nothing changed.

How many songs do you have ? Have you tried clearing app data and cache?

**Comment by Mk1378** [comment]
I have about 2500 songs.
Yes, I cleared data and cache but it's still the same.
The strange thing is that other tabs display all of my songs correctly.

**Comment by HardcodeCoder** [comment]
One possibility is that huawei changed the structure of `MediaStore` and the required data is not present (but this should result in a crash, which didn't happen). Also if no albums were found in the `MediaStore` a message `"No albums found"` should appear. 
Try the following:
1. Install the latest version, and clear data, cache
2. Go to albums tab and wait for ~1minute and see if albums appear. 
3. Also can you check whether clicking albums card in `Top Albums` section in home tab shows your songs correctly.

Lastly, if nothing works, can you please check with any other app and see if the issue exists. That should make it clear whether this is a device issue or Pulse Music app

**Comment by Mk1378** [comment]
1. I had already installed the latest version before my last comment.
2. I waited for 5 minutes but nothing changed. 
3. Yes,  clicking on albums in albums card shows the songs correctly.

I have other apps but never had an issue like this. 
Thanks

**Comment by HardcodeCoder** [comment]
I shall be providing a test build, if you would like to test.

**Comment by Mk1378** [comment]
That would be great, thanks.
