### ISSUE TITLE
When clicking on notification, now playing screen shows 2 now playing bars

### ISSUE THREAD

**Issue by PEPERSO** [HardcodeCoder/PulseMusic#83]
- **Android Version:** 9.0
- **Pulse Version:** 4.1.0

Steps to reproduce the bug:

1. Play a song
2. Close the app (keeping the song playing)
3. Click on the notification of the now playing song
4. Then you get on the now playing screen, with the previous/pause/next button at the bottom. But you have the exact same playing bar, buttons and song title at the top of screen, overlapping with album title (see screenshot below)
5. You can remove this by closing and reopenning the now playing screen

Note that it is not just a printing issue, since the now playing bar at the top is fully functionnal, you can play, pause and shows correct song title...

![Screenshot_20210307-125418_Pulse_Music](https://user-images.githubusercontent.com/49147850/110239040-30046f00-7f45-11eb-873d-9f6f3f30af17.png)

**Comment by HardcodeCoder** [comment]
Thanks for confirming. This issue has already been addressed in 15f6e67
