### ISSUE TITLE
[Bug] Songs do not play when opened from file manager

### ISSUE THREAD

**Issue by TheSilencedOne** [HardcodeCoder/PulseMusic#86]
Songs don't play when you open them from a file manager 

https://user-images.githubusercontent.com/78061111/110569559-a7432a00-8122-11eb-842c-34b16b5c1e52.mp4

**Comment by TheSilencedOne** [comment]
> Please mentions Android Version, OS and app version.
> Check if there is any log files in `/Android/data/com.hardcodecoder.pulsemusic/files`.

Android 7.1.2, FireOS 6.3.1.5, app version 4.1.0,
Logs:
[logcat_2021-03-10_08:21:55_.txt](https://github.com/HardcodeCoder/PulseMusic/files/6119780/logcat_2021-03-10_08.21.55_.txt)

**Comment by HardcodeCoder** [comment]
Does the same file shows up in Pulse Music and plays correctly?

**Comment by TheSilencedOne** [comment]
> Does the same file shows up in Pulse Music and plays correctly?

Yes everything plays correctly if you play it from the app

**Comment by TheSilencedOne** [comment]
It seems that version 4.1.1 didn't fix this issue, but i have a new crash log:
[GENERAL_logcat.txt](https://github.com/HardcodeCoder/PulseMusic/files/6166238/GENERAL_logcat.txt)

**Comment by HardcodeCoder** [comment]
Well, it's the same logs as before (just under a new file name which was added in the latest version). The issue has been identified, but a fix isn't available as of now.

The reason for the crash is 
`java.lang.NumberFormatException: For input string: "20201213T011915.000Z"`

Basically it seems to have invalid track duration(It is supposed to be an integer number, but the value extracted from the track is not a number). 

Interestingly another user has reported the same error with the same kind of duration `string`.

**Comment by HardcodeCoder** [comment]
Looks like this is a `DateTime` string. Can you check what is the exact duration of this audio file in seconds? That might help parse this string. But it is still weird as to why the audio duration returns a `DateTime` like string in the first place

**Comment by TheSilencedOne** [comment]
> Looks like this is a `DateTime` string. Can you check what is the exact duration of this audio file in seconds? That might help parse this string. But it is still weird as to why the audio duration returns a `DateTime` like string in the first place

213 Seconds

**Comment by HardcodeCoder** [comment]
Can't find any relationship between the extracted `DateTime` string and the actual duration. Looks like either the audio file is corrupted or the system's `MediaMetadataExtractor` is returning incorrect values. Whatever may be the case. This cannot be fixed as there is nothing the app can do in this case.
