### ISSUE TITLE
[Bug] App crashes when you click on music notification while in a playlist

### ISSUE THREAD

**Issue by TheSilencedOne** [HardcodeCoder/PulseMusic#87]
https://user-images.githubusercontent.com/78061111/110859943-2dc64b80-828a-11eb-9895-e4e724459244.mp4

Android 7.1.2, FireOS 6.3.1.5, app verison 4.1.0 

There wasnt any logs

**Comment by HardcodeCoder** [comment]
Please provide the steps to reproduce this. 
The steps in the video does not leads to a crash (in my testing). 
Try to clear data and cache, and then follow the steps that leads you to the crash and mention those steps.
Also, please let us know any settings that you have changed.

**Comment by TheSilencedOne** [comment]
> Please provide the steps to reproduce this.
> The steps in the video does not leads to a crash (in my testing).
> Try to clear data and cache, and then follow the steps that leads you to the crash and mention those steps.
> Also, please let us know any settings that you have changed.

Steps to reproduce:
Play a song from anywhere in the app, go into a playlist, pull down notifications, click on the music notification then it crashes. 
Ive tried clearing everything, I've used default settings and it still crashes,
It seems to only crash if you do it within roughly the first 30 seconds of playing the song, if you wait it opens the now playing screen as expected.

**Comment by PEPERSO** [comment]
On android 9.0, Pulse 4.1.1 I don't have the crash

**Comment by TheSilencedOne** [comment]
> On android 9.0, Pulse 4.1.1 I don't have the crash

I suspect that it might only be a issue on android 7.1.2

**Comment by TheSilencedOne** [comment]
Version 4.1.1 fixed this issue
