### ISSUE TITLE
Changing dark themes hides the songs in all lists

### ISSUE THREAD

**Issue by pokegamer5547** [HardcodeCoder/PulseMusic#88]
Changing the dark theme in settings sometimes causes all songs in lists to disappear. Restarting the app or changing the theme again fixes it.
Steps to reproduce the bug:
1: enable "turn on dark mode"
2: change the dark theme to anything else than previous one
3: go back, then the list shows "no tracks"
As I mentioned, restarting or changing theme again fixes it easily.

**Comment by HardcodeCoder** [comment]
Thanks for confirming the bug. This issue has already been fixed in 17bde20e4b5349555c3e3a6962b608958139f106.
