### ISSUE TITLE
Keep last play when quitting the app 

### ISSUE THREAD

**Issue by Porrumentzio** [HardcodeCoder/PulseMusic#97]
I use to play music shuffled, but when I open the app again after quitting it I have to tap again the shuffle button.
In my opinion, the app should keep the last play or playlist when quitting. This way, I wouldn't have to start the shuffle again each time.

This applies to any other situation, as it is expected that the app keeps playlist.

**Comment by HardcodeCoder** [comment]
Settings -> General -> Remember playlist.

**Comment by Porrumentzio** [comment]
There are two problems:
1) this does **not** save play position (minute and second)
2) this does **not** save queues or playlists:
    1) Play a playlist or shuffle and see which song comes later
    2) Quit the app, enter again and see that the playlist is not saved

**Comment by HardcodeCoder** [comment]
Please provide the specific device, OS and android version you are on. 
The "Remember Playlist" should save the entire playlist as well as the play time. 
Please attach any logs(which can be found in /Android/data/com.hardcodecoder.pulsemusic/files/) if available.

**Comment by Porrumentzio** [comment]
+ Xiaomi Redmin Note 4 X
+ /e/OS 0.15 (LineageOS fork)
+ Android 7.1.2 Nougat
+ PulseMusic 4.0.6

No logs on that directory.

That it, Remember playlist option only saves the last playing song, from the beginning.

**Comment by HardcodeCoder** [comment]
Please always update to the latest version before reporting a bug. 
Current latest release is V4.1.1 and you are using V4.0.6.
The specified functionality was added after V4.0.6.

**Comment by Porrumentzio** [comment]
Thanks! I use F-Droid's version and that is the last version

**Comment by HardcodeCoder** [comment]
Yes, there was some issue with f-droid (and hence V4.1.0 was not published) but after releasing V4.1.1, it seems to have been be fixed.

**Comment by Porrumentzio** [comment]
That's it! I had to un- and re-install and all worked well. Great app, thanks!
